<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="20149" started-at="2018-08-29T15:21:08Z" finished-at="2018-08-29T15:21:28Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="20149" started-at="2018-08-29T15:21:08Z" finished-at="2018-08-29T15:21:28Z">
      <class name="com.facebook.TestCases.LoginUI_Test">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="setUp" is-config="true" duration-ms="423" started-at="2018-08-29T20:51:07Z" finished-at="2018-08-29T20:51:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="BeforeTest" is-config="true" duration-ms="6373" started-at="2018-08-29T20:51:08Z" finished-at="2018-08-29T20:51:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="921" started-at="2018-08-29T20:51:14Z" finished-at="2018-08-29T20:51:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testOne() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testOne()[pri:1, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testOne" duration-ms="3656" started-at="2018-08-29T20:51:15Z" finished-at="2018-08-29T20:51:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOne -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="8" started-at="2018-08-29T20:51:19Z" finished-at="2018-08-29T20:51:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testOne status=SUCCESS method=LoginUI_Test.testOne()[pri:1, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="279" started-at="2018-08-29T20:51:19Z" finished-at="2018-08-29T20:51:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testOneTwo() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="SKIP" signature="testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testOneTwo" duration-ms="481" started-at="2018-08-29T20:51:19Z" finished-at="2018-08-29T20:51:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testOneTwo(LoginUI_Test.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOneTwo -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="206" started-at="2018-08-29T20:51:20Z" finished-at="2018-08-29T20:51:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testOneTwo status=SKIP method=LoginUI_Test.testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="314" started-at="2018-08-29T20:51:20Z" finished-at="2018-08-29T20:51:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testOneTwo() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="FAIL" signature="testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testOneTwo" duration-ms="464" started-at="2018-08-29T20:51:20Z" finished-at="2018-08-29T20:51:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testOneTwo(LoginUI_Test.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOneTwo -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="129" started-at="2018-08-29T20:51:21Z" finished-at="2018-08-29T20:51:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testOneTwo status=FAILURE method=LoginUI_Test.testOneTwo()[pri:2, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="389" started-at="2018-08-29T20:51:21Z" finished-at="2018-08-29T20:51:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testTwo() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testTwo()[pri:5, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testTwo" duration-ms="532" started-at="2018-08-29T20:51:21Z" finished-at="2018-08-29T20:51:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="1" started-at="2018-08-29T20:51:22Z" finished-at="2018-08-29T20:51:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testTwo status=SUCCESS method=LoginUI_Test.testTwo()[pri:5, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="334" started-at="2018-08-29T20:51:22Z" finished-at="2018-08-29T20:51:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testThree()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testThree()[pri:10, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testThree" duration-ms="508" started-at="2018-08-29T20:51:22Z" finished-at="2018-08-29T20:51:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="1" started-at="2018-08-29T20:51:23Z" finished-at="2018-08-29T20:51:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testThree status=SUCCESS method=LoginUI_Test.testThree()[pri:10, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="294" started-at="2018-08-29T20:51:23Z" finished-at="2018-08-29T20:51:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testFive()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="SKIP" signature="testFive()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testFive" duration-ms="553" started-at="2018-08-29T20:51:23Z" finished-at="2018-08-29T20:51:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testFive(LoginUI_Test.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFive -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="443" started-at="2018-08-29T20:51:24Z" finished-at="2018-08-29T20:51:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFive status=SKIP method=LoginUI_Test.testFive()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="309" started-at="2018-08-29T20:51:24Z" finished-at="2018-08-29T20:51:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testFive()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="FAIL" signature="testFive()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testFive" duration-ms="454" started-at="2018-08-29T20:51:24Z" finished-at="2018-08-29T20:51:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.TestCases.LoginUI_Test.testFive(LoginUI_Test.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFive -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="1370" started-at="2018-08-29T20:51:25Z" finished-at="2018-08-29T20:51:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFive status=FAILURE method=LoginUI_Test.testFive()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="register(java.lang.reflect.Method)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="register" is-config="true" duration-ms="336" started-at="2018-08-29T20:51:26Z" finished-at="2018-08-29T20:51:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.facebook.TestCases.LoginUI_Test.testFour()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method status="PASS" signature="testFour()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="testFour" duration-ms="464" started-at="2018-08-29T20:51:27Z" finished-at="2018-08-29T20:51:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method status="PASS" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="captureStatus" is-config="true" duration-ms="1" started-at="2018-08-29T20:51:27Z" finished-at="2018-08-29T20:51:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testFour status=SUCCESS method=LoginUI_Test.testFour()[pri:15, instance:com.facebook.TestCases.LoginUI_Test@4883b407] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="cleanUp" is-config="true" duration-ms="688" started-at="2018-08-29T20:51:27Z" finished-at="2018-08-29T20:51:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="tearDown" is-config="true" duration-ms="6041" started-at="2018-08-29T20:51:28Z" depends-on-methods="com.facebook.TestCases.LoginUI_Test.afterSuite" finished-at="2018-08-29T20:51:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.facebook.TestCases.LoginUI_Test@4883b407]" name="afterSuite" is-config="true" duration-ms="0" started-at="2018-08-29T20:51:28Z" finished-at="2018-08-29T20:51:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.facebook.TestCases.LoginUI_Test -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
